# Generated by Django 4.0.5 on 2022-06-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_drink_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='name',
        ),
    ]
